// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package payload

import "encoding/json"
import "fmt"
import "reflect"
import "time"

type Attachment struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// MimeType corresponds to the JSON schema field "mime_type".
	MimeType string `json:"mime_type" yaml:"mime_type" mapstructure:"mime_type"`

	// SizeBytes corresponds to the JSON schema field "size_bytes".
	SizeBytes int `json:"size_bytes" yaml:"size_bytes" mapstructure:"size_bytes"`

	// Type corresponds to the JSON schema field "type".
	Type AttachmentType `json:"type" yaml:"type" mapstructure:"type"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

type AttachmentType string

const AttachmentTypeFile AttachmentType = "file"
const AttachmentTypeScreenshot AttachmentType = "screenshot"

var enumValues_AttachmentType = []interface{}{
	"screenshot",
	"file",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AttachmentType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AttachmentType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AttachmentType, v)
	}
	*j = AttachmentType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Attachment) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mime_type"]; raw != nil && !ok {
		return fmt.Errorf("field mime_type in Attachment: required")
	}
	if _, ok := raw["size_bytes"]; raw != nil && !ok {
		return fmt.Errorf("field size_bytes in Attachment: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Attachment: required")
	}
	if _, ok := raw["url"]; raw != nil && !ok {
		return fmt.Errorf("field url in Attachment: required")
	}
	type Plain Attachment
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.SizeBytes {
		return fmt.Errorf("field %s: must be >= %v", "size_bytes", 0)
	}
	*j = Attachment(plain)
	return nil
}

type Client struct {
	// Locale corresponds to the JSON schema field "locale".
	Locale string `json:"locale" yaml:"locale" mapstructure:"locale"`

	// Referrer corresponds to the JSON schema field "referrer".
	Referrer *string `json:"referrer,omitempty" yaml:"referrer,omitempty" mapstructure:"referrer,omitempty"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`

	// UserAgent corresponds to the JSON schema field "user_agent".
	UserAgent string `json:"user_agent" yaml:"user_agent" mapstructure:"user_agent"`

	// Viewport corresponds to the JSON schema field "viewport".
	Viewport Viewport `json:"viewport" yaml:"viewport" mapstructure:"viewport"`

	// WidgetVersion corresponds to the JSON schema field "widget_version".
	WidgetVersion string `json:"widget_version" yaml:"widget_version" mapstructure:"widget_version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Client) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["locale"]; raw != nil && !ok {
		return fmt.Errorf("field locale in Client: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in Client: required")
	}
	if _, ok := raw["url"]; raw != nil && !ok {
		return fmt.Errorf("field url in Client: required")
	}
	if _, ok := raw["user_agent"]; raw != nil && !ok {
		return fmt.Errorf("field user_agent in Client: required")
	}
	if _, ok := raw["viewport"]; raw != nil && !ok {
		return fmt.Errorf("field viewport in Client: required")
	}
	if _, ok := raw["widget_version"]; raw != nil && !ok {
		return fmt.Errorf("field widget_version in Client: required")
	}
	type Plain Client
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Client(plain)
	return nil
}

type Context struct {
	// AppContext corresponds to the JSON schema field "app_context".
	AppContext map[string]interface{} `json:"app_context,omitempty" yaml:"app_context,omitempty" mapstructure:"app_context,omitempty"`

	// PageMetadata corresponds to the JSON schema field "page_metadata".
	PageMetadata map[string]interface{} `json:"page_metadata,omitempty" yaml:"page_metadata,omitempty" mapstructure:"page_metadata,omitempty"`
}

type Conversation struct {
	// Classification corresponds to the JSON schema field "classification".
	Classification ConversationClassification `json:"classification" yaml:"classification" mapstructure:"classification"`

	// Language corresponds to the JSON schema field "language".
	Language string `json:"language" yaml:"language" mapstructure:"language"`

	// Messages corresponds to the JSON schema field "messages".
	Messages []Message `json:"messages" yaml:"messages" mapstructure:"messages"`

	// SeverityGuess corresponds to the JSON schema field "severity_guess".
	SeverityGuess ConversationSeverityGuess `json:"severity_guess" yaml:"severity_guess" mapstructure:"severity_guess"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`

	// TagsSuggested corresponds to the JSON schema field "tags_suggested".
	TagsSuggested []string `json:"tags_suggested" yaml:"tags_suggested" mapstructure:"tags_suggested"`

	// TitleSuggestion corresponds to the JSON schema field "title_suggestion".
	TitleSuggestion string `json:"title_suggestion" yaml:"title_suggestion" mapstructure:"title_suggestion"`
}

type ConversationClassification string

const ConversationClassificationBug ConversationClassification = "bug"
const ConversationClassificationFeatureRequest ConversationClassification = "feature_request"
const ConversationClassificationOther ConversationClassification = "other"
const ConversationClassificationQuestion ConversationClassification = "question"

var enumValues_ConversationClassification = []interface{}{
	"bug",
	"feature_request",
	"question",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConversationClassification) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ConversationClassification {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ConversationClassification, v)
	}
	*j = ConversationClassification(v)
	return nil
}

type ConversationSeverityGuess string

const ConversationSeverityGuessCritical ConversationSeverityGuess = "critical"
const ConversationSeverityGuessHigh ConversationSeverityGuess = "high"
const ConversationSeverityGuessLow ConversationSeverityGuess = "low"
const ConversationSeverityGuessMedium ConversationSeverityGuess = "medium"
const ConversationSeverityGuessUnknown ConversationSeverityGuess = "unknown"

var enumValues_ConversationSeverityGuess = []interface{}{
	"low",
	"medium",
	"high",
	"critical",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConversationSeverityGuess) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ConversationSeverityGuess {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ConversationSeverityGuess, v)
	}
	*j = ConversationSeverityGuess(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Conversation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["classification"]; raw != nil && !ok {
		return fmt.Errorf("field classification in Conversation: required")
	}
	if _, ok := raw["language"]; raw != nil && !ok {
		return fmt.Errorf("field language in Conversation: required")
	}
	if _, ok := raw["messages"]; raw != nil && !ok {
		return fmt.Errorf("field messages in Conversation: required")
	}
	if _, ok := raw["severity_guess"]; raw != nil && !ok {
		return fmt.Errorf("field severity_guess in Conversation: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Conversation: required")
	}
	if _, ok := raw["tags_suggested"]; raw != nil && !ok {
		return fmt.Errorf("field tags_suggested in Conversation: required")
	}
	if _, ok := raw["title_suggestion"]; raw != nil && !ok {
		return fmt.Errorf("field title_suggestion in Conversation: required")
	}
	type Plain Conversation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.TitleSuggestion) > 80 {
		return fmt.Errorf("field %s length: must be <= %d", "title_suggestion", 80)
	}
	*j = Conversation(plain)
	return nil
}

type IntakePayload struct {
	// Attachments corresponds to the JSON schema field "attachments".
	Attachments []Attachment `json:"attachments,omitempty" yaml:"attachments,omitempty" mapstructure:"attachments,omitempty"`

	// Client corresponds to the JSON schema field "client".
	Client Client `json:"client" yaml:"client" mapstructure:"client"`

	// Context corresponds to the JSON schema field "context".
	Context *Context `json:"context,omitempty" yaml:"context,omitempty" mapstructure:"context,omitempty"`

	// Conversation corresponds to the JSON schema field "conversation".
	Conversation Conversation `json:"conversation" yaml:"conversation" mapstructure:"conversation"`

	// RoutingHint corresponds to the JSON schema field "routing_hint".
	RoutingHint *string `json:"routing_hint,omitempty" yaml:"routing_hint,omitempty" mapstructure:"routing_hint,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Submission corresponds to the JSON schema field "submission".
	Submission Submission `json:"submission" yaml:"submission" mapstructure:"submission"`

	// User corresponds to the JSON schema field "user".
	User User `json:"user" yaml:"user" mapstructure:"user"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IntakePayload) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["client"]; raw != nil && !ok {
		return fmt.Errorf("field client in IntakePayload: required")
	}
	if _, ok := raw["conversation"]; raw != nil && !ok {
		return fmt.Errorf("field conversation in IntakePayload: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in IntakePayload: required")
	}
	if _, ok := raw["submission"]; raw != nil && !ok {
		return fmt.Errorf("field submission in IntakePayload: required")
	}
	if _, ok := raw["user"]; raw != nil && !ok {
		return fmt.Errorf("field user in IntakePayload: required")
	}
	type Plain IntakePayload
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = IntakePayload(plain)
	return nil
}

type Message struct {
	// Content corresponds to the JSON schema field "content".
	Content string `json:"content" yaml:"content" mapstructure:"content"`

	// Role corresponds to the JSON schema field "role".
	Role MessageRole `json:"role" yaml:"role" mapstructure:"role"`

	// Ts corresponds to the JSON schema field "ts".
	Ts time.Time `json:"ts" yaml:"ts" mapstructure:"ts"`
}

type MessageRole string

const MessageRoleAssistant MessageRole = "assistant"
const MessageRoleUser MessageRole = "user"

var enumValues_MessageRole = []interface{}{
	"user",
	"assistant",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageRole) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MessageRole {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MessageRole, v)
	}
	*j = MessageRole(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Message) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["content"]; raw != nil && !ok {
		return fmt.Errorf("field content in Message: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return fmt.Errorf("field role in Message: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in Message: required")
	}
	type Plain Message
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Message(plain)
	return nil
}

type Submission struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// SubmittedAt corresponds to the JSON schema field "submitted_at".
	SubmittedAt time.Time `json:"submitted_at" yaml:"submitted_at" mapstructure:"submitted_at"`

	// TenantId corresponds to the JSON schema field "tenant_id".
	TenantId *string `json:"tenant_id,omitempty" yaml:"tenant_id,omitempty" mapstructure:"tenant_id,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Submission) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Submission: required")
	}
	if _, ok := raw["submitted_at"]; raw != nil && !ok {
		return fmt.Errorf("field submitted_at in Submission: required")
	}
	type Plain Submission
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Submission(plain)
	return nil
}

type User struct {
	// AuthMode corresponds to the JSON schema field "auth_mode".
	AuthMode UserAuthMode `json:"auth_mode" yaml:"auth_mode" mapstructure:"auth_mode"`

	// Custom corresponds to the JSON schema field "custom".
	Custom map[string]interface{} `json:"custom,omitempty" yaml:"custom,omitempty" mapstructure:"custom,omitempty"`

	// DisplayName corresponds to the JSON schema field "display_name".
	DisplayName *string `json:"display_name,omitempty" yaml:"display_name,omitempty" mapstructure:"display_name,omitempty"`

	// Email corresponds to the JSON schema field "email".
	Email *string `json:"email,omitempty" yaml:"email,omitempty" mapstructure:"email,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Verified corresponds to the JSON schema field "verified".
	Verified bool `json:"verified" yaml:"verified" mapstructure:"verified"`
}

type UserAuthMode string

const UserAuthModeAnonymous UserAuthMode = "anonymous"
const UserAuthModeEmail UserAuthMode = "email"
const UserAuthModeSso UserAuthMode = "sso"

var enumValues_UserAuthMode = []interface{}{
	"anonymous",
	"email",
	"sso",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserAuthMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserAuthMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_UserAuthMode, v)
	}
	*j = UserAuthMode(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *User) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["auth_mode"]; raw != nil && !ok {
		return fmt.Errorf("field auth_mode in User: required")
	}
	if _, ok := raw["verified"]; raw != nil && !ok {
		return fmt.Errorf("field verified in User: required")
	}
	type Plain User
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = User(plain)
	return nil
}

type Viewport struct {
	// H corresponds to the JSON schema field "h".
	H int `json:"h" yaml:"h" mapstructure:"h"`

	// W corresponds to the JSON schema field "w".
	W int `json:"w" yaml:"w" mapstructure:"w"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Viewport) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["h"]; raw != nil && !ok {
		return fmt.Errorf("field h in Viewport: required")
	}
	if _, ok := raw["w"]; raw != nil && !ok {
		return fmt.Errorf("field w in Viewport: required")
	}
	type Plain Viewport
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.H {
		return fmt.Errorf("field %s: must be >= %v", "h", 0)
	}
	if 0 > plain.W {
		return fmt.Errorf("field %s: must be >= %v", "w", 0)
	}
	*j = Viewport(plain)
	return nil
}
